USE [SCB_VOTUP]
GO

ALTER TABLE [dbo].[TB_MENSAGEM_ANCINE] DROP CONSTRAINT [FK__TB_MENSAG__SEA_I__6383C8BA]
GO

ALTER TABLE [dbo].[TB_MENSAGEM_ANCINE] DROP CONSTRAINT [FK__TB_MENSAG__SAL_C__628FA481]
GO

ALTER TABLE [dbo].[TB_MENSAGEM_ANCINE] DROP CONSTRAINT [FK__TB_MENSAG__BIL_I__619B8048]
GO

/****** Object:  Table [dbo].[TB_MENSAGEM_ANCINE]    Script Date: 11/07/2017 15:16:25 ******/
DROP TABLE [dbo].[TB_MENSAGEM_ANCINE]
GO

/****** Object:  Table [dbo].[TB_MENSAGEM_ANCINE]    Script Date: 11/07/2017 15:16:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_MENSAGEM_ANCINE](
	[MSA_DT_MSG] [date] NOT NULL,
	[MSA_DT_HORA_MSG] [datetime] NOT NULL,
	[BIL_ID] [bigint] NOT NULL,
	[SAL_CD_ANCINE] [varchar](20) NOT NULL,
	[SEA_ID] [bigint] NULL,
	[SEA_DT_HR_INICIO] [datetime] NULL,
	[MSA_TP_MSG] [varchar](1) NOT NULL,
	[MSA_CD_MSG] [varchar](4) NOT NULL,
	[MSA_TXT_MSG] [varchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MSA_DT_MSG] ASC,
	[BIL_ID] ASC,
	[MSA_DT_HORA_MSG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_MENSAGEM_ANCINE]  WITH NOCHECK ADD FOREIGN KEY([BIL_ID])
REFERENCES [dbo].[TB_BILHETERIA] ([BIL_ID])
GO

ALTER TABLE [dbo].[TB_MENSAGEM_ANCINE]  WITH NOCHECK ADD FOREIGN KEY([SAL_CD_ANCINE])
REFERENCES [dbo].[TB_SALA] ([SAL_CD_ANCINE])
GO

ALTER TABLE [dbo].[TB_MENSAGEM_ANCINE]  WITH NOCHECK ADD FOREIGN KEY([SEA_ID])
REFERENCES [dbo].[TB_SESSAO_ANCINE] ([SEA_ID])
GO


