USE SCB_SPCINE
GO

CREATE VIEW dbo.vw_PROT_ANALISE
AS
SELECT BIL_DIA_CIN, SAL_CD_ANCINE, BIL_PROT 
FROM TB_BILHETERIA 
WHERE BIL_PROT <> '' 
AND BIL_STATUS_PROT = 'A'
GROUP BY BIL_DIA_CIN, SAL_CD_ANCINE, BIL_PROT

GO