USE [SCB_SPCINE]
GO


CREATE TABLE [dbo].[TB_BIL_PROT_XML]
(
	[BIL_ID] [bigint] IDENTITY(1,1) NOT NULL,

	[EMP_CD_ANCINE] [varchar](20) NOT NULL,
	[SAL_CD_ANCINE] [varchar](20) NOT NULL,
	[BIL_DIA_CIN] [date] NOT NULL,
	
	[BIL_HOUVE_SES] [varchar](1) NOT NULL,
	[BIL_RETIF] [varchar](1) NOT NULL,
	[BIL_PROT] [varchar](50) NOT NULL,
	[BIL_ADIMP_SALA] [varchar](1) NOT NULL,
	
	[BIL_STATUS_PROT] [varchar](1) NOT NULL,

PRIMARY KEY CLUSTERED 
(
	[BIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TB_BILHETERIA]  WITH CHECK ADD FOREIGN KEY([EMP_CD_ANCINE])
REFERENCES [dbo].[TB_EMPRESA_COMPLEXO] ([EMP_CD_ANCINE])
GO

ALTER TABLE [dbo].[TB_BILHETERIA]  WITH CHECK ADD FOREIGN KEY([SAL_CD_ANCINE])
REFERENCES [dbo].[TB_SALA] ([SAL_CD_ANCINE])
GO


